Enhancement (ESAI): Add `esai-helper apply|delete default-strategy` subcommand to easily apply a default ESAI strategy

diff --git a/variants/v1.5.3153.0-bf2stats-2.3.3/esai-helper b/variants/v1.5.3153.0-bf2stats-2.3.3/esai-helper
--- a/variants/v1.5.3153.0-bf2stats-2.3.3/esai-helper
+++ b/variants/v1.5.3153.0-bf2stats-2.3.3/esai-helper
@@ -2,7 +2,7 @@
 set -eu
 
 usage() {
-    echo "$0: Get and apply ESAI Strategies.ai in levels/<level>/server.zip"
+    echo "esai-helper: Get and apply ESAI Strategies.ai in levels/<level>/server.zip"
     echo "Options:"
     echo "    -d|--dir                                      BF2 server installation directory. Defaults to '/server/bf2'"
     echo "    -m|--mod                                      Mod. E.g. 'bf2' or 'xpack'. Defaults to 'bf2'"
@@ -17,25 +17,29 @@ usage() {
     echo "    levels                                        Get all available levels"
     echo "    mods                                          Get all available mods"
     echo "    strategies                                    Get all available ESAI strategies"
-    echo "  apply|delete [options] [arg...]"
-    echo "    <level> <gamemode> <strategy>  Apply the specified ESAI strategy to a specified gamemode"
+    echo "  apply|delete [subcommand]"
+    echo "    default-strategy <strategy>                   Apply a default ESAI strategy for all levels."
+    echo "                                                  This is the default strategy if a level-strategy is not found for a level"
+    echo "    level-strategy <level> <gamemode> <strategy>  Apply the specified ESAI strategy to a specified gamemode"
     echo "                                                  of a specified level's server.zip"
     echo "    -f|--file <space_delimited_file>              Apply ESAI strategies based on a space-delimited file"
     echo "                                                  Format per line: <level> <gamemode> <strategy>"
     echo "                                                  Use '#' for comments"
     echo "Examples:"
-    echo "  $0 -m bf2 get gamemodes"
-    echo "  $0 -m xpack get gamemodes"
-    echo "  $0 -m bf2 get maplist"
-    echo "  $0 -m bf2 get level-strategies"
-    echo "  $0 -m bf2 get level-strategiescontent"
-    echo "  $0 -m bf2 get levels"
-    echo "  $0 -m bf2 get mods"
-    echo "  $0 -m bf2 get strategies"
-    echo "  $0 -m bf2 apply highway_tampa gpm_cq 32 mediumfca"
-    echo "  $0 -m bf2 apply -f esai-optimized-strategies.txt"
-    echo "  $0 -m bf2 delete highway_tampa gpm_cq 32 mediumfca"
-    echo "  $0 -m bf2 delete -f esai-optimized-strategies.txt"
+    echo "  esai-helper -m bf2 get gamemodes"
+    echo "  esai-helper -m xpack get gamemodes"
+    echo "  esai-helper -m bf2 get maplist"
+    echo "  esai-helper -m bf2 get level-strategies"
+    echo "  esai-helper -m bf2 get level-strategiescontent"
+    echo "  esai-helper -m bf2 get levels"
+    echo "  esai-helper -m bf2 get mods"
+    echo "  esai-helper -m bf2 get strategies"
+    echo "  esai-helper -m bf2 apply default-strategy mediumfca"
+    echo "  esai-helper -m bf2 apply level-strategy highway_tampa gpm_cq 32 mediumfca"
+    echo "  esai-helper -m bf2 apply -f strategies.txt"
+    echo "  esai-helper -m bf2 delete default-strategy mediumfca"
+    echo "  esai-helper -m bf2 delete level-strategy highway_tampa gpm_cq 32 mediumfca"
+    echo "  esai-helper -m bf2 delete -f strategies.txt"
 }
 # Exit if we got no options
 if [ $# -eq 0 ]; then usage; exit 1; fi
@@ -117,11 +121,7 @@ while test $# -gt 0; do
             esac
             ;;
         apply|delete)
-            if [ "$1" = 'apply' ]; then
-                APPLY=1
-            else
-                DELETE=1
-            fi
+            SUBCOMMAND="$1"
             shift
             if [ "$#" = 0 ]; then
                 echo "Missing options or arguments"
@@ -129,14 +129,27 @@ while test $# -gt 0; do
                 exit 1
             fi
             case "$1" in
-                -f|--file)
-                    shift
-                    if [ "$#" -gt 0 ]; then
-                        FILE="$1"
-                        shift
+                default-strategy)
+                    if [ "$SUBCOMMAND" = 'apply' ]; then
+                        APPLY_DEFAULT_STRATEGY=1
+                    else
+                        DELETE_DEFAULT_STRATEGY=1
                     fi
+                    shift
+                    STRATEGY="${1:-}"
+                    if [ -z "$STRATEGY" ]; then
+                        echo "Please specify an ESAI strategy an argument. E.g. mediumfcapb"
+                        exit 1
+                    fi
+                    shift
                     ;;
-                *)
+                level-strategy)
+                    if [ "$SUBCOMMAND" = 'apply' ]; then
+                        APPLY_LEVEL_STRATEGY=1
+                    else
+                        DELETE_LEVEL_STRATEGY=1
+                    fi
+                    shift
                     LEVEL="${1:-}"
                     if [ -z "$LEVEL" ]; then
                         echo "Please specify a level as the first argument. E.g. dalian_plant"
@@ -162,6 +175,23 @@ while test $# -gt 0; do
                     fi
                     shift
                     ;;
+                -f|--file)
+                    if [ "$SUBCOMMAND" = 'apply' ]; then
+                        APPLY_FILE=1
+                    else
+                        DELETE_FILE=1
+                    fi
+                    shift
+                    if [ "$#" -gt 0 ]; then
+                        FILE="$1"
+                        shift
+                    fi
+                    ;;
+                *)
+                    echo "Invalid option '$1'" 1>&2
+                    usage
+                    exit 1
+                    ;;
             esac
             ;;
         *)
@@ -181,9 +211,12 @@ GET_LEVEL_STRATEGIESCONTENT=${GET_LEVEL_STRATEGIESCONTENT:-}
 GET_LEVELS=${GET_LEVELS:-}
 GET_MODS=${GET_MODS:-}
 GET_STRATEGIES=${GET_STRATEGIES:-}
-APPLY=${APPLY:-}
-DELETE=${DELETE:-}
-FILE=${FILE:-}
+APPLY_DEFAULT_STRATEGY=${APPLY_DEFAULT_STRATEGY:-}
+DELETE_DEFAULT_STRATEGY=${DELETE_DEFAULT_STRATEGY:-}
+APPLY_LEVEL_STRATEGY=${APPLY_LEVEL_STRATEGY:-}
+DELETE_LEVEL_STRATEGY=${DELETE_LEVEL_STRATEGY:-}
+APPLY_FILE=${APPLY_FILE:-}
+DELETE_FILE=${DELETE_FILE:-}
 LEVEL=${LEVEL:-}
 GAMEMODE=${GAMEMODE:-}
 SIZE=${SIZE:-}
@@ -269,6 +302,7 @@ if [ -n "$GET_LEVEL_STRATEGIESCONTENT" ]; then
         STRATEGIES_AI=$( unzip -l "$i" | grep -iE "GameModes/[^/]+/[0-9]+/[^/]+/Strategies.ai" | awk '{print $4}' | sort -n | uniq || true )
         if [ -n "$STRATEGIES_AI" ]; then
             for s in $STRATEGIES_AI; do
+                echo "Content of $s in $i:" >&2
                 unzip -p "$i" "$s"
             done
         else
@@ -286,9 +320,38 @@ if [ -n "$GET_STRATEGIES" ]; then
     find . | grep -E "mods/$MOD/esai/mapfiles/[^/]+/[^/]+/strategies.ai" | cut -d '/' -f7 | sort -n
 fi
 
-if [ -n "$APPLY" ] || [ -n "$DELETE" ]; then
+if [ -n "$APPLY_DEFAULT_STRATEGY" ]; then
+    # A trick not found in ESAI readmes
+    # The default ESAI strategy is used when there is no ESAI strategy for a particular level.
+    # According to Void, the original author of ESAI, it's easy to add the default ESAI strategy for all maps:
+    # 1. All except the last two lines of an ESAI strategy (i.e. mods/bf2/esai/mapfiles/*/<strategy>/strategies.ai) goes into aidefaultstrategies.ai
+    # 2. The last two lines go into aidefaultstrategiesadd.ai
+    STRATEGIES_AI=$( find "$DIR" | grep -E "mods/$MOD/esai/mapfiles/[^/]+/$STRATEGY/strategies.ai" | head -n1 || true )
+    if [ -z "$STRATEGIES_AI" ]; then
+        echo "No such strategy: $STRATEGY"
+        echo "To get a list of available strategies, run:"
+        echo "   esai-helper -m "$MOD" get strategies"
+        exit 1
+    fi
+    CONTENT=$( cat "$STRATEGIES_AI" )
+    LINE_COUNT=$( echo "$CONTENT" | wc -l )
+    echo "Applying $STRATEGIES_AI to $DIR/mods/$MOD/ai/aidefaultstrategies.ai">&2
+    echo "$CONTENT" | head -n $(( $LINE_COUNT - 2 )) > "$DIR/mods/$MOD/ai/aidefaultstrategies.ai"
+    echo "Applying $STRATEGIES_AI to $DIR/mods/$MOD/ai/aidefaultstrategiesadd.ai">&2
+    echo "$CONTENT" | tail -n 2 > "$DIR/mods/$MOD/ai/aidefaultstrategiesadd.ai"
+fi
+
+if [ -n "$DELETE_DEFAULT_STRATEGY" ]; then
+    echo "Deleting a default ESAI strategy is not supported. The server needs a default strategy."
+    exit 1
+fi
+
+if [ -n "$APPLY_LEVEL_STRATEGY" ] || [ -n "$DELETE_LEVEL_STRATEGY" ] || [ -n "$APPLY_FILE" ] || [ -n "$DELETE_FILE" ]; then
     # Validation
-    if [ -n "$FILE" ]; then
+    if [ -n "$APPLY_LEVEL_STRATEGY" ] || [ -n "$DELETE_LEVEL_STRATEGY" ]; then
+        CONTENT="$LEVEL $GAMEMODE $SIZE $STRATEGY"
+    fi
+    if [ -n "$APPLY_FILE" ] || [ -n "$DELETE_FILE" ]; then
         if [ ! -f "$FILE" ]; then
             echo "No such file: $FILE"
             exit 1
@@ -298,52 +361,52 @@ if [ -n "$APPLY" ] || [ -n "$DELETE" ]; then
             echo "No ESAI strategies to apply in: $FILE"
             exit 1
         fi
-    else
-        CONTENT="$LEVEL $GAMEMODE $SIZE $STRATEGY"
     fi
     echo "$CONTENT" | while read -r LEVEL GAMEMODE SIZE STRATEGY; do
         SERVER_ZIP="$DIR/mods/$MOD/levels/$LEVEL/server.zip"
         if ! unzip -l "$SERVER_ZIP" | grep "GameModes/$GAMEMODE/$SIZE" > /dev/null; then
             echo "The gamemode '$GAMEMODE' does not exist in $SERVER_ZIP"
             echo "To get a list of available gamemodes, run:"
-            echo "   $0 get gamemodes"
+            echo "   esai-helper -m "$MOD" get gamemodes"
             exit 1
         fi
-        STRATEGIES_AI=$( find $DIR | grep -E "mods/$MOD/esai/mapfiles/[^/]+/$STRATEGY/strategies.ai" | head -n1 || true )
+        STRATEGIES_AI=$( find "$DIR" | grep -E "mods/$MOD/esai/mapfiles/[^/]+/$STRATEGY/strategies.ai" | head -n1 || true )
         if [ -z "$STRATEGIES_AI" ]; then
             echo "No such strategy: $STRATEGY"
             echo "To get a list of available strategies, run:"
-            echo "   $0 get strategies"
+            echo "   esai-helper -m "$MOD" get strategies"
             exit 1
         fi
     done
-fi
-if [ -n "$APPLY" ]; then
-    echo "$CONTENT" | while read -r LEVEL GAMEMODE SIZE STRATEGY; do
-        cd "$DIR/mods/$MOD/levels/$LEVEL"
-        SERVER_ZIP="$PWD/server.zip"
-        STRATEGIES_AI=$( find $DIR | grep -E "mods/$MOD/esai/mapfiles/[^/]+/$STRATEGY/strategies.ai" | head -n1 || true )
-        STRATEGIES_AI_DESTINATION_IN_ZIP="GameModes/$GAMEMODE/$SIZE/ai/Strategies.ai"
-        echo "Applying strategy $STRATEGIES_AI to $SERVER_ZIP at $STRATEGIES_AI_DESTINATION_IN_ZIP"
-        mkdir -p "$( dirname "$STRATEGIES_AI_DESTINATION_IN_ZIP" )" # Same layout as content of server.zip
-        cp -f "$STRATEGIES_AI" "$STRATEGIES_AI_DESTINATION_IN_ZIP"
-        zip -qru server.zip GameModes
-        rm -rf "$DIR/mods/$MOD/levels/$LEVEL/GameModes"
-    done
-fi
-if [ -n "$DELETE" ]; then
-    echo "$CONTENT" | while read -r LEVEL GAMEMODE SIZE STRATEGY; do
-        cd "$DIR/mods/$MOD/levels/$LEVEL"
-        SERVER_ZIP="$PWD/server.zip"
-        EXISTING_STRATEGIES_AI=$( unzip -l "$SERVER_ZIP" | grep -iE "GameModes/$GAMEMODE/$SIZE/(ai|AI)/Strategies.ai" | awk '{print $4}' || true )
-        if [ -n "$EXISTING_STRATEGIES_AI" ]; then
-            for i in $EXISTING_STRATEGIES_AI; do
-                echo "Removing existing strategy $i from $SERVER_ZIP at $i"
-                zip -q -d "$SERVER_ZIP" "$i"
-            done
-        else
-            echo "No existing strategy in: $SERVER_ZIP"
-            exit 1
-        fi
-    done
+
+    if [ -n "$APPLY_LEVEL_STRATEGY" ] || [ -n "$APPLY_FILE" ]; then
+        echo "$CONTENT" | while read -r LEVEL GAMEMODE SIZE STRATEGY; do
+            cd "$DIR/mods/$MOD/levels/$LEVEL"
+            SERVER_ZIP="$PWD/server.zip"
+            STRATEGIES_AI=$( find "$DIR" | grep -E "mods/$MOD/esai/mapfiles/[^/]+/$STRATEGY/strategies.ai" | head -n1 || true )
+            STRATEGIES_AI_DESTINATION_IN_ZIP="GameModes/$GAMEMODE/$SIZE/ai/Strategies.ai"
+            echo "Applying strategy $STRATEGIES_AI to $SERVER_ZIP at $STRATEGIES_AI_DESTINATION_IN_ZIP"
+            mkdir -p "$( dirname "$STRATEGIES_AI_DESTINATION_IN_ZIP" )" # Same layout as content of server.zip
+            cp -f "$STRATEGIES_AI" "$STRATEGIES_AI_DESTINATION_IN_ZIP"
+            zip -qru server.zip GameModes
+            rm -rf "$DIR/mods/$MOD/levels/$LEVEL/GameModes"
+        done
+    fi
+
+    if [ -n "$DELETE_LEVEL_STRATEGY" ] || [ -n "$DELETE_FILE" ]; then
+        echo "$CONTENT" | while read -r LEVEL GAMEMODE SIZE STRATEGY; do
+            cd "$DIR/mods/$MOD/levels/$LEVEL"
+            SERVER_ZIP="$PWD/server.zip"
+            EXISTING_STRATEGIES_AI=$( unzip -l "$SERVER_ZIP" | grep -iE "GameModes/$GAMEMODE/$SIZE/(ai|AI)/Strategies.ai" | awk '{print $4}' || true )
+            if [ -n "$EXISTING_STRATEGIES_AI" ]; then
+                for i in $EXISTING_STRATEGIES_AI; do
+                    echo "Removing existing strategy $i from $SERVER_ZIP at $i"
+                    zip -q -d "$SERVER_ZIP" "$i"
+                done
+            else
+                echo "No existing strategy in: $SERVER_ZIP"
+                exit 1
+            fi
+        done
+    fi
 fi
